services:
  - type: web
    name: backend
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: "mongodb+srv://rodolfo:84471528@cluster0.gqmq7.mongodb.net/portFl?retryWrites=true&w=majority&appName=Cluster0"
